name: CI-CD

on: [push]

env:
  PWDMONGO: ${{ secrets.PWDMONGO }}

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build API
        run: npm run build

      - name: Run API-Test
        run: npm run server-test&

      - name: Wait for API start
        run: sleep 10s
        shell: bash

      - name: Run Test
        run: npm run test